name: nodecv-devel
version: 0.1
summary: node-opencv development package
description: |
  This snap provides nodejs packages for developing opencv applications
  using Javascript.
confinement: strict
grade: devel

apps:
  node:
    command: env \
      NODE_PATH=$SNAP/lib/node_modules \
      node
    plugs: [ hardware-observe, home, network, network-bind, camera ]

parts:
  # Part installs Node.js and selected supporting modules
  nodejs:
    plugin: nodejs
    node-packages:
      # Useful node modules
      - express
      - opencv
      - socket.io
    # installs dependencies required by OpenCV
    build-packages: [ build-essential, cmake, git, libgtk2.0-dev, pkg-config, libavcodec-dev, libavformat-dev, libswscale-dev, python-dev, python-numpy, libtbb2, libtbb-dev, libjpeg-dev, libpng12-dev, libtiff5-dev, libjasper-dev, libdc1394-22-dev, libopencv-dev ]
    build: |
      echo 'node.js packages have been installed in' $SNAPCRAFT_PART_INSTALL
    filesets:
      exports:
        # stage only the bin/ and lib/ folders
        - bin/
        - lib/
    stage: [ $exports ]
